services:
  postgres:
    container_name: postgres_patos
    image: postgres
    environment:
      POSTGRES_DB: patos_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-network
    restart: unless-stopped

  app:
    build: .
    container_name: desafio_patos_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_patos:5432/patos_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
volumes:
  postgres:
    driver: local